//
// Generated file, do not edit! Created by opp_msgc 4.1 from overlay/aimd/IncreaseTimer.msg.
//

#ifndef _INCREASETIMER_M_H_
#define _INCREASETIMER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>overlay/aimd/IncreaseTimer.msg</tt> by opp_msgc.
 * <pre>
 * message IncreaseTimer
 * {
 *     int target;
 * }
 * </pre>
 */
class IncreaseTimer : public ::cMessage
{
  protected:
    int target_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IncreaseTimer&);

  public:
    IncreaseTimer(const char *name=NULL, int kind=0);
    IncreaseTimer(const IncreaseTimer& other);
    virtual ~IncreaseTimer();
    IncreaseTimer& operator=(const IncreaseTimer& other);
    virtual IncreaseTimer *dup() const {return new IncreaseTimer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getTarget() const;
    virtual void setTarget(int target_var);
};

inline void doPacking(cCommBuffer *b, IncreaseTimer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IncreaseTimer& obj) {obj.parsimUnpack(b);}


#endif // _INCREASETIMER_M_H_
