//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/datatest/../../overlay/basic/LookupExt.msg.
//

#ifndef _LOOKUPEXT_M_H_
#define _LOOKUPEXT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <simtime_t.h>
// }}



/**
 * Class generated from <tt>applications/datatest/../../overlay/basic/LookupExt.msg</tt> by opp_msgc.
 * <pre>
 * packet LookupExt {
 *     int hops;
 *     int pathNodes[];
 *     int sequence_id;
 *     simtime_t senttime;
 * }
 * </pre>
 */
class LookupExt : public ::cPacket
{
  protected:
    int hops_var;
    int *pathNodes_var; // array ptr
    unsigned int pathNodes_arraysize;
    int sequence_id_var;
    simtime_t senttime_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LookupExt&);

  public:
    LookupExt(const char *name=NULL, int kind=0);
    LookupExt(const LookupExt& other);
    virtual ~LookupExt();
    LookupExt& operator=(const LookupExt& other);
    virtual LookupExt *dup() const {return new LookupExt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getHops() const;
    virtual void setHops(int hops_var);
    virtual void setPathNodesArraySize(unsigned int size);
    virtual unsigned int getPathNodesArraySize() const;
    virtual int getPathNodes(unsigned int k) const;
    virtual void setPathNodes(unsigned int k, int pathNodes_var);
    virtual int getSequence_id() const;
    virtual void setSequence_id(int sequence_id_var);
    virtual simtime_t getSenttime() const;
    virtual void setSenttime(simtime_t senttime_var);
};

inline void doPacking(cCommBuffer *b, LookupExt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LookupExt& obj) {obj.parsimUnpack(b);}


#endif // _LOOKUPEXT_M_H_
