//
// Generated file, do not edit! Created by opp_msgc 4.1 from overlay/basic/TimeoutMessage.msg.
//

#ifndef _TIMEOUTMESSAGE_M_H_
#define _TIMEOUTMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>overlay/basic/TimeoutMessage.msg</tt> by opp_msgc.
 * <pre>
 * message TimeoutMessage
 * {
 *   unsigned int seq_id;  
 * }
 * </pre>
 */
class TimeoutMessage : public ::cMessage
{
  protected:
    unsigned int seq_id_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TimeoutMessage&);

  public:
    TimeoutMessage(const char *name=NULL, int kind=0);
    TimeoutMessage(const TimeoutMessage& other);
    virtual ~TimeoutMessage();
    TimeoutMessage& operator=(const TimeoutMessage& other);
    virtual TimeoutMessage *dup() const {return new TimeoutMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSeq_id() const;
    virtual void setSeq_id(unsigned int seq_id_var);
};

inline void doPacking(cCommBuffer *b, TimeoutMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TimeoutMessage& obj) {obj.parsimUnpack(b);}


#endif // _TIMEOUTMESSAGE_M_H_
