//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/datatest/DataMsg.msg.
//

#ifndef _DATAMSG_M_H_
#define _DATAMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>applications/datatest/DataMsg.msg</tt> by opp_msgc.
 * <pre>
 * enum DataMessageType 
 * {
 *     DATATEST_DATA = 1;
 * }
 * </pre>
 */
enum DataMessageType {
    DATATEST_DATA = 1
};

/**
 * Class generated from <tt>applications/datatest/DataMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet DataMsg {
 *     int type enum (DataMessageType);
 * }
 * </pre>
 */
class DataMsg : public ::cPacket
{
  protected:
    int type_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DataMsg&);

  public:
    DataMsg(const char *name=NULL, int kind=0);
    DataMsg(const DataMsg& other);
    virtual ~DataMsg();
    DataMsg& operator=(const DataMsg& other);
    virtual DataMsg *dup() const {return new DataMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type_var);
};

inline void doPacking(cCommBuffer *b, DataMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DataMsg& obj) {obj.parsimUnpack(b);}


#endif // _DATAMSG_M_H_
